# Generated by Django 4.2.2 on 2023-06-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_report',
        ),
        migrations.AddField(
            model_name='project',
            name='repor_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='report_comment',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
