# Generated by Django 4.2.2 on 2023-06-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_user_myuser'),
        ('project', '0002_remove_comment_user_report_project_repor_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.myuser'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.myuser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owener_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.myuser'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.myuser'),
        ),
    ]
