# Generated by Django 4.2.2 on 2023-06-10 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_rename_user_email_comment_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="repor_count",
            new_name="report_count",
        ),
        migrations.AddField(
            model_name="projects",
            name="created_at",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
