# Generated by Django 4.2.2 on 2023-06-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_image_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminproject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
            ],
        ),
    ]
