# Generated by Django 4.2.2 on 2023-06-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_alter_myuser_image"),
        ("project", "0007_adminproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="report_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_state", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.myuser",
                    ),
                ),
            ],
        ),
    ]
