# Generated by Django 4.2.2 on 2023-06-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_alter_comment_report_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
