# Generated by Django 4.2.2 on 2023-06-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_comment_user_report_project_repor_count_and_more'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
