# Generated by Django 4.2.2 on 2023-06-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_myuser_delete_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='facebook_profile',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='static/images/profile/user-1.jpg', upload_to='static/images/profile/'),
        ),
    ]
