# Generated by Django 4.2.2 on 2023-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_myuser_facebook_profile_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(upload_to='static/images/profile/'),
        ),
    ]
