# Generated by Django 4.2.2 on 2023-06-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='facebook_profile',
            field=models.CharField(max_length=200),
        ),
    ]
