# Generated by Django 4.2.2 on 2023-06-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_myuser_facebook_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='facebook_profile',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
